# Generated by Django 3.2.5 on 2021-07-06 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Tipo',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Id',
        ),
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='nulo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='serieProducto',
            field=models.CharField(default='nulo', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
