# Generated by Django 3.2.5 on 2021-07-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210705_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='serieProducto',
            field=models.CharField(max_length=30),
        ),
    ]
