# Generated by Django 3.2.5 on 2021-07-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210705_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='serieProducto',
            new_name='serie',
        ),
    ]
